version: '3.1' 

services:
  bmd-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin111
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod

  bmd-backend:
    build:
      context: ../../best_meeting_day/
      dockerfile: ./docker/modules/bmd-base/Dockerfile
    image: bmd-backend:v1_0_3
    volumes:
      - config-volume:/opt/app/config
    depends_on:
      - bmd-mongo

  bmd-admin:
    build:
      context: ../../best_meeting_day/
      dockerfile: ./docker/modules/bmd-admin/Dockerfile
    image: bmd-admin:v1_0_3
    volumes:
      - config-volume:/opt/app/config

  bmd-nginx:
    build:
      context: ../../best_meeting_day/
      dockerfile: ./docker/modules/bmd-nginx/Dockerfile
    image: bmd-ngix:v1_0_3
    ports:
      - "80:80"

volumes:
  config-volume:
    driver: local
    driver_opts:
      type: none
      device: '/Users/a17540258/IdeaProjects/best_meeting_day/docker/modules'
      o: bind


# Exaple for resource limit
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '1'
    #      memory: 900M
    #    reservations:
    #      cpus: '1'
    #      memory: 900M
