server:
  port: 8080

spring:
  application:
    name: bmd-base
  main:
    allow-bean-definition-overriding: true
  #webflux:
  #  date-format: dd.MM.yyyy

bmd:
  db:
    port: 27017
    dbname: bmdbase
    host: 192.168.99.100
    username: dev
    password: dev
  mode: demo
