server:
  port: 8080

spring:
  application:
    name: bmd-base
  main:
    allow-bean-definition-overriding: true
  #webflux:
  #  date-format: dd.MM.yyyy

bmd:
  #date-format: dd.MM.yyyy
  db:
    port: 27017
    dbname: bmdbase
    host: localhost

