server:
  port: 8081

spring:
  application:
    name: boot-admin
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      context-path: "/sba"
      ui:
        public-url: http://localhost:8081/sba
